### ISSUE TITLE
Nim 1.1.1 NIUP Issues

### ISSUE THREAD

**Issue by ScriptBasic** [dariolah/niup#1]
I discovered a couple issues using Nim 1.1.1 with **niup**. It works fine in Nim 1.0.4.

These constants throw a hard error with no line number reference and a message from error.nim about not being KIND.  (indents not being shown)

const
    isshift* = iup_isshift
    iscontrol* = iup_iscontrol
    isbutton1* = iup_isbutton1
    isbutton2* = iup_isbutton2
    isbutton3* = iup_isbutton3
    isdouble* = iup_isdouble
    isalt* = iup_isalt
    issys* = iup_issys
    isbutton4* = iup_isbutton4
    isbutton5* = iup_isbutton5

The **with** doesn't work either in 1.1.1.

  withPIhandle vbox:
    "ALIGNMENT" "ACENTER"
    "GAP"       "10"
    "MARGIN"    "10x10"

**Comment by dariolah** [comment]
I'm not following devel branch, only stable releases of Nim.

First issue looks like it could be fixed with new c2nim, problem code is result of c2nim.

Second is possibly  because of changes in macros API, I need changelog for Nim.

Once there is new stable Nim release, I'll update NIUP.

Thank you for notice

**Comment by dariolah** [comment]
Last commit fixed building with Nim 1.2
